// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irgrvzecmoisjnhjptzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZ3J2emVjbW9pc2puaGpwdHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NzA5MTIsImV4cCI6MjA5MzI0NjkxMn0.wOKqdZZFNPn0zddZWAYGfcfsaRm3OaAZ355Js6H_kbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
