// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tamjlnbuaofgaqbnvyxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbWpsbmJ1YW9mZ2FxYm52eXhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTcxNTcsImV4cCI6MjA3MTM5MzE1N30.YIWzvPbBjcqWWgujsYAtYGMN2qg4Elef-5bBwkJUe1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/runtimeClient";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});